# Spring配置
spring:
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 8484
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
logging:
  level:
    com.renren: debug
    org.springframework: warn